#Alacritty:

env:
  TERM: alacritty

window:
  opacity: 0.5
  padding:
    x: 25
    y: 25

    dynamic_padding:  true
    decoration: none

font:
  normal:
    family: Source Code Pro

  bold:
    family: Source Code Pro

  italic:
    family: Source Code Pro

  bold_italic:
    family: Source Code Pro

  size: 7

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xa9b1d6'

  # Normal colors
  normal:
    black:   '0x32344a'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan:    '0x449dab'
    white:   '0x9699a8'

  # Bright colors
  bright:
    black:   '0x444b6a'
    red:     '0xff7a93'
    green:   '0xb9f27c'
    yellow:  '0xff9e64'
    blue:    '0x7da6ff'
    magenta: '0xbb9af7'
    cyan:    '0x0db9d7'
    white:   '0xacb0d0'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x212121'
    cursor: '0xeeffff'

  indexed_colors:
    - { index: 16, color: '0xf78c6c' }
    - { index: 17, color: '0xff5370' }
    - { index: 18, color: '0x303030' }
    - { index: 19, color: '0x353535' }
    - { index: 20, color: '0xb2ccd6' }
    - { index: 21, color: '0xeeffff' }

cursor:
  style:
    shape: Block
    blinking: On

#   unfocused_hollow: false

live_config_reload: true

key_bindings:

  - { key: Key0, mods: Control, action: ResetFontSize }

  - { key: Equals, mods: Control, action: IncreaseFontSize }

  - { key: Minus, mods: Control, action: DecreaseFontSize }

  - { key: V, mods: Control, action: Paste }

  - { key: P, mods: Control, action: Copy }
